### PR TITLE
Fixed Compilation Errors

### PR DESCRIPTION
**Pull request by gupta-himanshu**
The compilation errors in the Enricher are fixed now. However, few test suites are still failing, hence they need review for the fix.

### CODE REVIEW

**Review by aahmedg — CHANGES_REQUESTED** [review]
adjust the pr, and the branch names, the convention we follow is
branch name:
feature|bugfix|hotfix/{ticket#}_{humanFriendlyName}

pr name:
{ticket#}: {humanFriendlyName}e.g 

feature/SOPHI-122: Fixed compilation error after upgrade

**Review by dmatth — CHANGES_REQUESTED** [review]
I don't know what this is. The as-forked master branch of the snowplow code generates compile errors? That can't be right. When I look at the public Snowplow master-branch copy of the first file here, the Beam-module Enrich.scala, it has many changes from what I see here, apparently from commits done last June and July, which we for some reason have not picked up.
This is not your fault, of course, I think you've inherited the result of a not-very-successful attempt by Piyush to fix the major problems with his earlier PR.
I think this has reached the point where it might make sense to give up on that work, and redo it from scratch in a brand-new PR based on a clean current copy of the Snowplow master branch.

**Comment by gupta-himanshu** [comment]
Agreed, so does that mean I need to create a new branch from `snowplow/enrich master`? And make the required changes on that. Because the `globeandmail/enrich's master` branch does not have a clean git history.

**Comment by gupta-himanshu** [comment]
Also, I have created another PR for it, with the proper branch name. Should I cancel both of these PRs?

**Comment by dmatth** [comment]
I think the first thing to do here is try to get our repo in sync with the repo it was forked from, so our master branch looks just like theirs. I haven't done this before, but it seems to be not too complicated - on your local copy of this TGAM repo, first configure the public Snowplow repo as 'upstream' (`git remote add upstream git://github.com/snowplow/enrich.git`), then `git fetch upstream` to make sure you've got all their commits, then `git checkout upstream/master` should get you on the branch we want to use. I've just done this myself on my local, results seem OK. Final step would be to push that branch to overwrite the master branch on the TGAM repo, but I haven't got that to work yet. want to give it a try?
(also, FYI, I created branch https://github.com/globeandmail/enrich/tree/master.with.some.piyush.changes as a backup copy of the current unhealthy master, in case we need to refer to it later)

**Comment by gupta-himanshu** [comment]
Sure, but syncing the `master` branch of `snowplow/enrich` with `master` branch of `globeandmail/enrich` has an issue. The last commit on `snowplow/enrich`s master branch was made on 20 Nov 2020, that commit is already present in the `globeandmail/enrich`s master branch. Hence pulling the changes from `snowplow` would not make any difference.

Since the work that Piyush did was added on top the last commit of `snowplow` hence the git history cannot change. The only way I can see is to create a separate branch from `snowplow/enrich`s master branch and update it with the required changes. This would give us a clear separation of the work we need in a faster and efficient way.

Please let me know your thoughts on it.

**Comment by gupta-himanshu** [comment]
This PR is not required anymore. Hence closing it.

**Pull request closed without merging**
